---
version: '2.3'

services:
    loader:
        restart: always
        image: rushiai/auto-reloader:20251022
        build: ./_docker
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /usr/bin/docker:/usr/bin/docker
            - ./work:/work
            - ./keys:/root/.ssh

        ports:
            - 9870:9870

        working_dir: /work
        # uncomment this to run the check-push.sh script instead of web hook
        #command: /scripts/check-push.sh
        environment:
            - TZ=Asia/Shanghai
            - VERB=1
            #- TIMEOUT=120
               # default timeout of possible pending cmd is 120s
            #- SLEEP_TIME=360
               # default sleep time is 360s